---

#- name: remove android studio folder and reinstall
#  file:
#        path: /opt/android-studio/
#        state: absent

- name: install android emulator
  apt:
        name: google-android-emulator-installer
        state: latest

- name: Verify android studio folder
  stat:
    path: /opt/android-studio/
  register: studioFolder


- name: install android-studio
  block:
    - name: copy android-studio installer
      get_url:
            url: "ftp://10.1.255.17/{{ androidstudio_filename }}"
            dest: "/opt/{{ androidstudio_filename }}"

    - name: install android-studio apt dependencies
      apt:
        name: [gcc-multilib, g++-multilib, libc6-dev-i386, qemu-kvm, mesa-utils]
        state: latest

    - name: unzip android-studio to /opt
      unarchive:
        copy: false
        src: "/opt/{{ androidstudio_filename }}"
        dest: /opt/
        mode: "0755"

    - name: copy android studio template
      template:
        src: android-studio.desktop
        dest: /usr/share/applications/


    - name: update system icons
      block:
        - name: gtk update
          command: gtk-update-icon-cache /usr/share/icons/hicolor/

        - name: desktop database
          command: update-desktop-database -q

        - name: xdg menu
          command: xdg-desktop-menu forceupdate

    - name: remove arquivo compactado
      file:
        path: "/opt/{{ androidstudio_filename }}"
        state: absent
  when:  not studioFolder.stat.exists
