---
- name: alteração de sources.list
  template:
    src: apt.sources.list/sources.list
    dest: /etc/apt/sources.list


# Adiciona Chaves
- name: repo key vbox
  ansible.builtin.get_url:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    dest: /etc/apt/keyrings/vbox_old.asc


- name: repo key vbox
  ansible.builtin.get_url:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    dest: /etc/apt/keyrings/vbox.asc

         
- name: repo key vscode
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/vscode.asc
   

- name: pgadmin repo key
  ansible.builtin.get_url:
    url: https://www.pgadmin.org/static/packages_pgadmin_org.pub
    dest: /etc/apt/keyrings/pgadmin.asc

- name: pgadmin repo key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc


# Adiciona repositorios

- name: add pgadmin repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/pgadmin.asc] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/{{ ansible_distribution_release }} pgadmin4 main"
    state: present
    filename: pgadmin4

- name: add docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker.list

- name: "apt | ensure Google linux signing key present"
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: "apt | ensure Google chrome repo present"
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: "google-chrome"
    state: present
    update_cache: yes

 
- name: apt update and upgrade
  apt:
    update-cache: yes
    upgrade: full
