---
- name: alteração de sources.list
  template:
    src: apt.sources.list/sources.list
    dest: /etc/apt/sources.list

- name: remove vscode repo /tmp
  file:
    path: /etc/apt/sources.list.d/vscode.list
    state: absent

# Adiciona Chaves

- name: "apt | ensure Google linux signing key present"
  apt_key: 
          url: https://dl-ssl.google.com/linux/linux_signing_key.pub 
          state: present

- name: virtualbox.yml - add virtualbox key
  apt_key:
          url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
          state: present

- name: Add virtualbox key
  apt_key:
          url: https://www.virtualbox.org/download/oracle_vbox.asc
          state: present

- name: Add VScode key
  apt_key:
          url: https://packages.microsoft.com/keys/microsoft.asc
          state: present
         
# Adiciona repositorios

- name: remove old repo source
  file:
    path: "/etc/apt/sources.list.d/{{ item }}.list"
    state: absent
  loop: 
    - download_virtualbox_org_virtualbox_debian
    - ppa_libreoffice_libreoffice_still_focal


- name: verify source list file libreoffice
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/libreoffice.list
  register: libreoffice_stat


- name: libreoffice.yml - latest repo
  apt_repository:
    repo: ppa:libreoffice/libreoffice-still
    filename: "libreoffice"
    state: present
  when: libreoffice_stat.stat.islnk is not defined

- name: remove repositorio do android-studio
  apt_repository:
        repo: ppa:maarten-fonville/android-studio
        state: absent

- name: alteração de sources.list.d files
  template:
      src: "apt.sources.list/{{ item }}"
      dest: "/etc/apt/sources.list.d/{{ item }}"
  loop:
    - virtualbox.list
    - libreoffice.list
    - google-chrome.list
    - vscode.list
 
- name: apt update and upgrade
  apt:
    update-cache: yes
    upgrade: full