---
- name: remove old arduino files
  file:
        path: "{{ item }}"
        state: absent
  loop:
        - /usr/share/applications/arduino-arduinoide.desktop
        - "{{ ARDUINO_FOLDER }}"
        - "{{ ARDUINO_FOLDER_EXTRACTED }}"
  when: arduino_update
  
- name: create arduino folder to new executable
  file:
        path: "{{ ARDUINO_FOLDER }}"
        state: directory
  register: arduino_folder
        

- name:
  block:
    - name: create arduino desktop file
      template: 
        src: arduino.desktop
        dest: /usr/share/applications/arduino.desktop

    - name: copy arduino executable
      get_url:
        url: "ftp://{{ ftp_server }}/{{ ARDUINO_FILE }}.{{ ARDUINO_FILE_EXTENSION }}"
        dest: "{{ ARDUINO_FOLDER }}/{{ ARDUINO_FILE }}.{{ ARDUINO_FILE_EXTENSION }}"

    - name: extract arduino executable
      unarchive:
        src: "{{ ARDUINO_FOLDER }}/{{ ARDUINO_FILE }}.{{ ARDUINO_FILE_EXTENSION }}"
        dest: "{{ ARDUINO_FOLDER }}" 
        remote_src: yes

    - name: copy arduino icon
      get_url:
        url: "ftp://{{ ftp_server }}/arduino.png"
        dest: "{{ ARDUINO_FOLDER }}/arduino.png"

    - name: remove file arduino
      file:
        path: "{{ ARDUINO_FOLDER }}/chrome-sandbox"
        state: present
        mode: '4755'
        owner: root
        state: file
    
    - name: remove file arduino
      file:
        path: "{{ ARDUINO_FOLDER }}/{{ ARDUINO_FILE }}.{{ ARDUINO_FILE_EXTENSION }}"
        state: absent

  when: arduino_folder.changed == True



# - name: copia e instala o arduino
#   block:
#       - name: copia arduino  to /tmp
#         get_url: 
#           url: "ftp://10.1.255.17/{{ ARDUINO_FILE }}"
#           dest: "/tmp/{{ ARDUINO_FILE }}"
          
#       - name:  Descompacta arduino installer
#         unarchive:
#             src: "/tmp/{{ ARDUINO_FILE }}"
#             dest: /opt/
#             remote_src: yes
   
#       - name: executa instalador do arduino
#         shell:
#             cmd: "{{ ARDUINO_FOLDER }}/install.sh"
#   when: arduino_stat.stat.exists == False
  

