---
- name: copy background image
  copy: 
        src: background.png
        dest: /opt/background.png


- name: configure dconf profile
  template:
    src: wallpaper_profile
    dest: /etc/dconf/profile/user

- name: create profile db local directory
  file:
    path: /etc/dconf/db/local.d/ 
    state: directory
    owner: root
    mode: 0755

- name: config directory settings
  template:
    src: wallpaper_config
    dest: /etc/dconf/db/local.d/00-background

- name: create profile db/lock local directory
  file:
    path: /etc/dconf/db/local.d/locks/
    state: directory
    owner: root
    mode: 0755

- name: create lock for wallpaper settings
  template:
    src: wallpaper_lock
    dest: /etc/dconf/db/local.d/locks/lockdown

- name: update dconf database
  command: dconf update

