- name: Install default browsers 
  block:
    - name: latest browsers
      apt:
              name: [google-chrome-stable, firefox]
              state: latest
      when: ansible_distribution == 'Ubuntu'

    - name: latest browsers
      apt:
              name: [google-chrome-stable, firefox-esr]
              state: latest
      when: ansible_distribution == 'Debian'

    - name: copy google chrome template .desktop
      template:
            src: google-chrome.desktop
            dest: /usr/share/applications/google-chrome.desktop 