---

- name: Set default time to shutdown computers at Midday
  cron: name=script_exec minute=*/5 state=absent job="flock -n /root/updater /root/main.sh"


- name: configure 
  command: dpkg --configure -a


- name: correct command
  command: dpkg --remove --force-remove-reinstreq android-studio-2021.2.1 android-studio
  ignore_errors: True

- name: remove android-studio
  command: dpkg --remove --force-remove-reinstreq android-studio
  ignore_errors: True