---

- name: Crontab.yml - Set default time to shutdown computers at night
  cron: name=atNight hour=02 minute=00 state=present job="/sbin/shutdown -h 5"

- name: clear-saved.yml - install cron remove older than 45 day files
  cron:
          name: remove older files
          job: find /save/* -mtime +45 -execdir rm -rf -- '{}' \;
          special_time: hourly

- name: update vscode
  cron:
    name: apt update vscode
    job: apt install vscode -y
    special_time: hourly

