---

- name: update all packages
  apt:  
        upgrade: dist

- name: default-softwares.yml - Default softwares to labs network
  apt: 
        name: [wireshark, tcpdump, arp-scan, dsniff, ipcalc, filezilla, traceroute, nbtscan, nmap, iptraf, curl]
        state: latest

- name: Default softwares to lab programmin
  apt:
           name: [python3-pip, g++, gcc, git, virtualenv, codeblocks, pipx]
           state: latest


- name: Common Softwares
  apt:
          name: [rar, unrar, p7zip-full]
          state: latest

- name: Audio and Video softwares
  apt:
          name: [vlc, audacity, smplayer, pitivi, gimp, inkscape, audacity]
          state: latest

- name: system utilities
  apt:
          name: [vim, okular, git, gparted, sysstat, rsync, htop, fortune, cowsay, cmatrix, figlet, exfat-fuse]
          state: latest

- name: extra utilities
  apt:
          name: [umbrello, remmina, dia]
          state: latest



