---

- name: install latest libreoffice
  apt:
          name: libreoffice
          state: latest

- name: install translations
  apt:
          name: libreoffice-l10n-pt-br,libreoffice-style-galaxy
          state: latest

