---

- name: configure postgresql user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
      name: aluno
      password: aluno
      role_attr_flags: CREATEDB
      state: present
  environment:
      PGOPTIONS: "-c password_encryption=scram-sha-256"




