- name: pip upgrade pip3
  pip:
       name: pip
       executable: pip3
       state: latest

- name: install jupyter
  become: True
  become_user: aluno
  pip:
       name: "{{ item }}"
       executable: pip3
       state: latest
       umask: "0022"
  loop:
    - jupyter
    - matplotlib
    - sklearn
    - pandas
    - seaborn
    - numpy
    - geopandas==0.7.0
    - geobr
    - tqdm
    - streamlit
    - dash
    - sklearn
    - matplotlib

- name: install node steps
  block:
    - name: verify nvm installation
      stat:
        path: /home/aluno/.nvm/
      register: nvm_status

    - name: configure nvm
      become: true
      become_user: aluno
      become_method: sudo
      ignore_errors: true
      block:
        - name: install nvm linux -- nvm bin
          shell: > 
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          # args:
          #   executable: /bin/bash
          #   chdir: "{{ /home/aluno/ }}"
          #   creates: "/home/aluno/.nvm/nvm.sh"

        - name: install "node"
          shell: >
            . /home/aluno/.nvm/nvm.sh && nvm install --lts
          args:
            executable: /bin/bash
            chdir: "/home/aluno/"
            creates: "/home/aluno/.nvm/versions/node"
      when: nvm_status.stat.islnk is not defined
    

    
  



