---
- name: programs.yml - install softwares
  apt:
          name: "{{ item }}"
          state: latest
  loop:
          - geany
          - geany-plugins
          - fpc
          - php-cli
          - python3-virtualenv
          - codeblocks
          - aptitude
          - php-cli
          - php-mysql
          - php-pgsql
          - screen
          - links
          - net-tools
          - iproute2
          - netcat
          - python3-pymysql
          - tcpdump
          - tshark
          - mariadb-client

- name: postgresql.yml - install postgresql plugins 
  apt: 
        name: [python3-mysqldb, python3-psycopg2, postgresql] 
  
- name: install pgadmin4
  apt:
        name: pgadmin4-desktop
        state: latest

- name: mysql.yml - install mysql-server
  apt:
          name: mysql-server, python3-pymysql
          state: latest

- name: copy google chrome template .desktop
  template:
        src: google-chrome.desktop
        dest: /usr/share/applications/google-chrome.desktop 

- name: java.yml - install java jdk
  apt:
          name: default-jdk
          state: latest

- name: install java
  apt:
          name: openjdk-11-jdk-headless
          state: latest


- name: remove softwares 
  apt:
          name: "{{ item }}"
          state: absent
  loop:
          - kdeconnect
          - thunderbird


- name: install qgis
  apt:
        name: qgis
        state: present
 
- name: verify vscode installation
  stat:
    path: /usr/share/code/code
  register: code_bin

- name: install vscode
  block:
    - name: copy vscode installer
      get_url:
            url: ftp://10.1.255.17/vscode.deb
            dest: /opt/vscode.deb

    - name: install vscode
      apt:
            deb: /opt/vscode.deb

    - name: remove vscode installer
      file:
            name: /opt/vscode.deb
            state: absent
  when: code_bin.stat.islnk is not defined


- name: verify Insomnia REST client installation
  stat:
        path: /opt/Insomnia/
  register: insomnia_folder

- name: install insomnia if folder not exists
  block:
        - name: get insomnia installer from FTP
          get_url: 
                url: ftp://10.1.255.17/Insomnia.Core-8.6.1.deb
                dest: /tmp/Insomnia.Core-8.6.1.deb

        - name: install with apt module
          apt:
                deb: /tmp/Insomnia.Core-8.6.1.deb
             
  when: insomnia_folder.stat.exists is defined

- name: verify projectlibre installation
  stat:
        path: /opt/Insomnia/
  register: project_folder

- name: install project if folder not exists
  block:
        - name: get project installer from FTP
          get_url: 
                url: ftp://10.1.255.17/projectlibre_1.9.3-1.deb
                dest: /tmp/projectlibre_1.9.3-1.deb

        - name: install with apt module
          apt:
                deb: /tmp/projectlibre_1.9.3-1.deb
             
  when: project_folder.stat.exists is defined
 
  
