---
- name: sudoers.yml - Set includedir in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: Create sudoers
  template: 
        src: sudoers.j2
        dest: "/etc/sudoers.d/{{ sudoers_file }}"
        mode: 0440
        owner: root
        group: root
        validate: "/usr/sbin/visudo -cf %s"

