---

# Importante que a task do android studio seja executada para criar o grupo
- name: username.yml - update aluno user
  user:
          groups: cdrom,dip,plugdev,lxd,kvm,dialout
          name: aluno
          password: "{{ aluno_pass }}"
          state: present
          shell: /bin/bash

- name: create/update ti user
  user:
          append: yes
          groups: sudo,cdrom,dip,plugdev,lxd,kvm
          name: ti
          password: "{{ ti_pass }}"
          shell: /bin/bash

# - name: create ssh dir folder for ti
#   file:
#     path: /home/ti/.ssh/
#     mode: 0700
#     owner: ti
#     state: directory

# - name: ensure key is present to ti user
#   copy:
#           src: id_rsa.pub
#           dest: "/home/ti/.ssh/id_rsa.pub"
#           mode: 0600
#           owner: ti

- name: ensure key is installed to ti user
  ansible.posix.authorized_key:
    key: https://raw.githubusercontent.com/lucasvruchel/linux-lab-ansible/master/files/id_rsa.pub
    user: ti
    state: present
  