---

- name: configure extension pack EULA
  debconf:
          name: virtualbox-ext-pack
          question: virtualbox-ext-pack/license
          value: 'true'
          vtype: select

- name: add/update virtualbox packages
  apt:
       name: '{{ item }}'
       state: present
  loop:
      - virtualbox-6.1
      - virtualbox-ext-pack
