---

- name: virtualbox.yml - add virtualbox key
  apt_key:
          url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
          state: present

- name: virtualbox.yml - add virtualbox key
  apt_key:
          url: https://www.virtualbox.org/download/oracle_vbox.asc
          state: present


- name: add virtualbox repository
  apt_repository:
      state: present
      repo: deb https://download.virtualbox.org/virtualbox/debian focal contrib


- name: configure extension pack EULA
  debconf:
          name: virtualbox-ext-pack
          question: virtualbox-ext-pack/license
          value: 'true'
          vtype: select

- name: add/update virtualbox packages
  apt:
       name: '{{ item }}'
       state: latest
  loop:
      - virtualbox-qt
      - virtualbox-6.1
      - virtualbox-dkms
      - virtualbox-ext-pack