---

- name: install mysql workbench
  block:
    - name: copy mysql workbench installer
      get_url:
            url: "ftp://{{ ftp_server }}/{{ workbench_file }}"
            dest: "/opt/{{ workbench_file }}"
    
    - name: install workbench 
      apt: 
        deb: "/opt/{{ workbench_file }}"

    - name: remove mysql workbench installer
      file:
        path: "/opt/{{ workbench_file }}.deb"
        state: absent
