---
# handlers file for .

- name: restart ssh
  systemd:
        name: ssh
        state: restarted


- name: network reload
  systemd:
    name: NetworkManager
    state: reloaded

- name: update cache
  apt:
          update_cache: yes

- name: freeze status change
  command: shutdown -r now
